### ISSUE TITLE
Search errors for long SMILES codes

### ISSUE THREAD

**Issue by JonasSchaub** [mSorok/NaturalProductsOnline#38]
It happened multiple times to me that when I search for a quite long SMILES code, the search function runs into an error ('An error occurred...'). And when this happens, I also cannot start a new search, I have to reload the page. 
One example is the SMILES code 'O=C(O)CC(O)(C)CC(=O)OC1COC(OC2C(O)C(OC(OC3C(O)C(O)C(OC4CC5CCC6C(CCC7(C)C6CC8OC9(OCC(C)CC9)C(C)C87)C5(C)CC4O)OC3CO)C2OC%10OC(CO)C(O)C(O)C%10O)CO)C(O)C1O'.

**Comment by mSorok** [comment]
Question: are you doing this search in the header search bar, or in the "Structure search" part?

**Comment by JonasSchaub** [comment]
I'm doing it in the header search bar. 
In the structure search with the option 'Exact match (by canonical SMILES)' it seems to be working fine.

**Comment by mSorok** [comment]
Ok, so I managed to find several little bugs that were appearing with few exceptional queries:
- it was an encoding problem, appearing only with the "simple search" because of the % + digits in the long and complex SMILES
- I also finally corrected the possibility to search again after a result or an error.

Thank you for pointing this issue out!
