### ISSUE TITLE
compounds

### ISSUE THREAD

**Issue by uzmas2022** [mSorok/NaturalProductsOnline#84]
many compounds in the database are distorted.

Also, the names are missing for most of them. How do we search more about the compound
<img width="1356" alt="Untitled1" src="https://user-images.githubusercontent.com/103169751/162132355-e2d915ad-231a-41df-9aac-7e904a7f9fed.png">

**Comment by steinbeck** [comment]
Thanks for letting us know. It helps a lot to get the identifiers of ideally all or at least a few of the molecules that you found were distorted. Please provide them if you can. 
Furthermore, are you sure that those 3D coordinates are from the COCONUT website and not generated by your studio visualiser?

With regard to names, you are right. The problem is that a lot of sources did not supply names. We can easily generate IUPAC names, but you would not necessarily want to search for them. Searching for structures might be the best option.
